# Site settings
title: Docker MCP Community Portal
description: A community-driven collection of Docker Model Context Protocol servers
baseurl: "" # Empty for local development, set to "/docker-mcp-portal" for GitHub Pages
url: "https://ajeetraina.github.io" # Replace with your GitHub Pages URL
github_username: ajeetraina

# Build settings
markdown: kramdown
highlighter: rouge
safe: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  labs:
    output: true
    permalink: /labs/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_docs"
    values:
      layout: "doc"
  - scope:
      path: "_labs"
    values:
      layout: "lab"
  - scope:
      path: "_data"
    values:
      layout: "none"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - CONTRIBUTING.md
  - LICENSE
  
# Configure sass
sass:
  style: compressed

# Make sure data files get processed
data_dir: _data