name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_preview:
    runs-on: ubuntu-latest
    name: Build PR Preview
    if: github.event.action != 'closed'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # We need full history for proper versioning
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      
      - name: Build Jekyll site
        run: |
          # Create unique base URL for preview
          echo "url: https://ajeetraina.github.io" >> _config.yml
          echo "baseurl: /mcp-portal/pr-preview/pr-${{ github.event.pull_request.number }}" >> _config.yml
          
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: ./_site
          destination_dir: pr-preview/pr-${{ github.event.pull_request.number }}
          keep_files: true
          publish_branch: gh-pages
          commit_message: "Deploy PR preview for PR #${{ github.event.pull_request.number }}"
      
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Check if we've already commented
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: issueNumber,
            });
            
            const botComment = comments.data.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('PR Preview deployed')
            );
            
            const commentBody = `✅ PR Preview deployed successfully!\n\n🔍 Preview your changes: [https://ajeetraina.github.io/mcp-portal/pr-preview/pr-${issueNumber}/](https://ajeetraina.github.io/mcp-portal/pr-preview/pr-${issueNumber}/)\n\nThis preview will update automatically when you push new changes to your PR.`;
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: botComment.id,
                body: commentBody,
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issueNumber,
                body: commentBody,
              });
            }

  cleanup_preview:
    runs-on: ubuntu-latest
    name: Cleanup PR Preview
    if: github.event.action == 'closed'
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.PAT }}
      
      - name: Delete preview directory
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if [ -d "pr-preview/pr-${{ github.event.pull_request.number }}" ]; then
            git rm -rf pr-preview/pr-${{ github.event.pull_request.number }}
            git commit -m "Remove PR preview for #${{ github.event.pull_request.number }}"
            git push
          else
            echo "No preview directory found to clean up"
            exit 0
          fi