name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_preview:
    runs-on: ubuntu-latest
    name: Build PR Preview
    permissions:
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      
      - name: Build Jekyll site
        run: |
          # Build site with proper config
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Upload PR preview artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-preview-${{ github.event.pull_request.number }}
          path: _site
          retention-days: 14
      
      - name: Find PR comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: PR Preview
      
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🔍 PR Preview
            
            Your PR preview has been built successfully! To view it:
            
            1. Click on the "Details" link next to the "PR Preview Deployment" check in the PR checks section
            2. On the Actions run page, scroll to the bottom and click on the "pr-preview-${{ github.event.pull_request.number }}" artifact
            3. Download and extract the zip file
            4. Open the `index.html` file in your browser
            
            This preview will update automatically when you push new changes to your PR.
          edit-mode: replace
          reactions: rocket