name: PR Preview Deployment (GitHub Pages)

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

# Add top-level permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  build_preview:
    runs-on: ubuntu-latest
    name: Build PR Preview
    if: github.event.action != 'closed'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # We need full history for proper versioning
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      
      - name: Build Jekyll site
        run: |
          # Customize base URL for preview deployment
          echo "url: https://mcp.collabnix.com" >> _config.yml
          echo "baseurl: /pr-preview/pr-${{ github.event.pull_request.number }}" >> _config.yml
          
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: pr-preview/pr-${{ github.event.pull_request.number }}
          keep_files: true
          publish_branch: gh-pages
          commit_message: "Deploy PR preview for PR #${{ github.event.pull_request.number }}"
      
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: PR Preview
      
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🔍 PR Preview
            
            Your PR preview has been deployed! View it live at:
            
            👉 [https://mcp.collabnix.com/pr-preview/pr-${{ github.event.pull_request.number }}/](https://mcp.collabnix.com/pr-preview/pr-${{ github.event.pull_request.number }}/)
            
            This preview will update automatically when you push new changes to your PR.
          edit-mode: replace
          reactions: rocket

  cleanup_preview:
    runs-on: ubuntu-latest
    name: Cleanup PR Preview
    if: github.event.action == 'closed'
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Delete preview directory
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if [ -d "pr-preview/pr-${{ github.event.pull_request.number }}" ]; then
            git rm -rf "pr-preview/pr-${{ github.event.pull_request.number }}"
            git commit -m "Remove PR preview for #${{ github.event.pull_request.number }}"
            git push
          else
            echo "No preview directory found to clean up"
            exit 0
          fi
