name: Update MCP Server Star Counts

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
          
      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/update_mcp_servers_stars.py
        
      - name: Commit changes if any
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add _data/mcp_servers.yml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub star counts for MCP servers"
          git push
