name: Update MCP Servers

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  update-servers:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml github3.py requests
          
      - name: Run update script
        run: python scripts/update_mcp_servers_github_only.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
